#!/bin/bash

# Wait for network and background services to finish
sleep = sleep 10

# Set screen to never timeout
xset = xset -dpms

# Update and upgrade the system to ensure chromium is up-to-date without manual updates
update = sudo apt update
upgrade = sudo apt upgrade -y

# Launching Chromium in incognito to avoid any popups, running in the background
chromium-browser --start-fullscreen --start-maximized --noerrdialogs --disable-infobars --incognito http://10.4.12.91/library_tv/d5.php &

# Hide the mouse from the screen
unclutter = unclutter -idle 1

# Pull other script which will refresh the page every 100 seconds and restart the device every 24 hours
/home/cpltv/.config/lxsession/LXDE-pi/pagerefresh.sh
